image: maven:3.5.4-jdk-8

stages:
 - build
 - test
 - analyse
 - deploy

unit_test:
 stage: test
 script:
 - mvn clean test
 rules:
 - if: '$CI_COMMIT_BRANCH == "main"'

build:
 stage: build
 script:
 - mvn compile

sonar:
 stage: analyse
 image: maven:3.6.3-jdk-11
 script:
 - mvn verify sonar:sonar -Dsonar.projectKey=jeej_project


services:
 - postgres:12.2-alpine

variables:
 POSTGRES_DB: topkek
 POSTGRES_USER: 'jeej'
 POSTGRES_PORT: 5432
 POSTGRES_HOST_AUTH_METHOD: trust
 DATABASE_URL_TEST=postgres://jeej:@postgres:5432/topkek