image: maven:3.5.4-jdk-8

stages:
 - build
 - test
 - analyse
 - deploy

unit_test:
 stage: test
 script:
 - mvn clean test
 rules:
 - if: '$CI_COMMIT_BRANCH == "main"

build:
	stage: build
	script:
	- mvn compile

sonar:
 tage: analyse
 script:
 - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=jeej_project
 image: maven:3.6.3-jdk-11
