image: maven:3.5.4-jdk-8

unit_test:
	stage: test
	script:
	- mvn clean test
	rules:
	- if: '$CI_COMMIT_BRANCH == "main"'
	export DATABASE_URL_TEST=postgres://gael:@postgres:5432/qieam
	POSTGRES_HOST_AUTH_METHOD: trust